// v2/src/core/app.jsx
import {StrictMode} from 'react';

import { Router, Route, Switch } from "wouter";

import Home from 'view/home/home.view.jsx';
import Group from 'view/group/group.view.jsx';
import Crypto from 'view/extra/crypto/crypto.view.jsx';

export default function App() {
    return (
        <StrictMode>
            <Router>
                <Switch>
                    <Route path="/" component={Home} />
                    <Route path="/group/:name" component={Group} />
                    <Route path="/extra/crypto" component={Crypto} />
                    <Route>404, Not Found!</Route>
                </Switch>
            </Router>
        </StrictMode>
    );
};

// src/core/app.svelte
<script>
    import {Route} from 'tinro'; 

    import Docs from '../view/docs.svelte';

    import HttpRouter from '../view/http/http.svelte';
    import CryptoRouter from '../view/crypto/crypto.svelte';
</script>

<Route>
    <Route path="/">
        <div>HOME</div>
    </Route>
    <Route path="/docs/*">
        <Route path="/">
            <Docs />
        </Route>
    </Route>
    <Route path="/extra/*">
        <HttpRouter />
        <CryptoRouter />
    </Route>
    <Route fallback>NOT FOUND</Route>
</Route>
